import Foundation

/// Client side of the experimental false-alarm learner.
///
/// The learner itself lives at `learner/` in the repo root and is deliberately kept out of the
/// app: it is offline, stdlib-only Python, and reads the judgement log to produce one portable
/// artefact, `focus_policy.json`. This type is the only thing the running app knows about it — a
/// small, defensive reader turning that artefact into three answers:
///
/// - `promptSuffix` — extra lines appended to the classifier prompt ("the user has confirmed that
///   Khan Academy in Safari IS part of maths revision")
/// - `preAllow` — skip the check entirely for a signature the user has repeatedly excused
/// - `blockThreshold` — don't block an off-task verdict below this confidence
///
/// Everything here fails soft. The policy file is generated by a separate program; if it is
/// missing, stale, from a future schema, or corrupt, the app must behave exactly as it does with
/// no learning at all.
enum LearnedPolicy {

    /// The schema this client understands. A policy claiming a newer schema is ignored rather than
    /// half-read — a partially-understood policy is worse than none, because the parts we drop
    /// might be the safety limits.
    static let supportedSchema = 1

    /// Hard client-side floor. Even if a policy file asks for a higher bar, we never require more
    /// than this much confidence to block. This is the ceiling on how far learning may erode the
    /// monitor, and it lives here — in the app — so hand-editing the generated file cannot lift it.
    static let maxThreshold = 0.85
    static let maxSuffixChars = 1200
    static let maxAgeDays: TimeInterval = 60

    struct Decision {
        var promptSuffix: String = ""
        var preAllow: Bool = false
        var blockThreshold: Double = 0
    }

    static var fileURL: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)
            .first ?? FileManager.default.temporaryDirectory
        return base.appendingPathComponent("LockoutProtocol/focus_policy.json")
    }()

    private static var cachedModified: Date?
    private static var cached: [String: Any]?

    /// Read + cache the policy file, reloading only when it changes on disk.
    static func load() -> [String: Any] {
        let attrs = try? FileManager.default.attributesOfItem(atPath: fileURL.path)
        guard let modified = attrs?[.modificationDate] as? Date else {
            cachedModified = nil; cached = nil
            return [:]
        }
        if cachedModified == modified, let cached { return cached }

        var data: [String: Any] = [:]
        if let raw = try? Data(contentsOf: fileURL),
           let obj = try? JSONSerialization.jsonObject(with: raw) as? [String: Any] {
            data = obj
        }
        if data["schema"] as? Int != supportedSchema { data = [:] }
        // A policy learned from a person's habits two months ago is describing a different
        // person's week. Expire it rather than trusting it indefinitely.
        if let generated = data["generated_at"] as? Double,
           Date().timeIntervalSince1970 - generated > maxAgeDays * 86400 {
            data = [:]
        }

        cachedModified = modified
        cached = data
        return data
    }

    /// The one call the monitor makes. Always returns a usable value.
    ///
    /// The matching itself is done by the learner's own `apply()` in Python, which the macOS app
    /// cannot call. So the compiled artefact carries a pre-expanded `decisions` map keyed by
    /// `"<task-cluster>|<app>"` — the learner does the clustering offline, and every client just
    /// looks up a string. That keeps the Swift and Kotlin ports to a lookup rather than a
    /// reimplementation of the matching logic, which would inevitably drift.
    static func decide(task: String, app: String, title: String = "") -> Decision {
        let policy = load()
        guard !policy.isEmpty else { return Decision() }

        guard let decisions = policy["decisions"] as? [String: [String: Any]] else {
            return Decision()
        }
        let key = lookupKey(task: task, app: app)
        guard let entry = decisions[key] ?? decisions["*|\(app)"] else { return Decision() }

        var decision = Decision()
        decision.promptSuffix = String((entry["prompt_suffix"] as? String ?? "")
            .prefix(maxSuffixChars))
        decision.preAllow = entry["pre_allow"] as? Bool ?? false
        let raw = (entry["block_threshold"] as? NSNumber)?.doubleValue ?? 0
        decision.blockThreshold = min(max(raw, 0), maxThreshold)

        // A pre-allow keyed only on the app, with no title evidence behind it, is too blunt to
        // honour — it would silently un-watch a whole app. Require the learner to have said which
        // titles it meant.
        if decision.preAllow, let patterns = entry["title_patterns"] as? [String], !patterns.isEmpty {
            let lowered = title.lowercased()
            decision.preAllow = patterns.contains { lowered.contains($0.lowercased()) }
        }
        return decision
    }

    static func promptSuffix(task: String, app: String, title: String = "") -> String {
        decide(task: task, app: app, title: title).promptSuffix
    }

    /// Normalise a task the same way the learner does when it builds the keys: lowercase, letters
    /// and digits only, drop stopwords and words of two characters or fewer, keep the first four,
    /// join with "-". Both sides must agree character for character, so it is small on purpose and
    /// mirrored in `learner/policy.py:lookup_key`.
    ///
    /// The app id is lower-cased too. On Windows it already is (`chrome.exe`), but a macOS bundle
    /// id is not — `com.google.Chrome` — and the learner lower-cases before writing the key, so
    /// skipping it here would make every macOS lookup miss silently.
    static func lookupKey(task: String, app: String) -> String {
        let stop: Set<String> = ["the", "a", "an", "my", "for", "on", "to", "of", "and", "in",
                                 "working", "work", "doing", "do", "some", "this", "that"]
        // Rebuilt into a String before splitting rather than chained off `map`. Mapping a String
        // yields [Character]; splitting that yields [ArraySlice<Character>], and `String.init` has
        // enough overloads for those that the compiler gives up on the tail of the chain with
        // "ambiguous use of 'prefix'". Naming the intermediate costs one line and removes the
        // guesswork.
        let flattened = String(task.lowercased().map { $0.isLetter || $0.isNumber ? $0 : " " })
        let words: [String] = flattened
            .split(separator: " ")
            .map { String($0) }
            .filter { !stop.contains($0) && $0.count > 2 }
        let appKey = app.trimmingCharacters(in: .whitespaces).lowercased()
        return "\(words.prefix(4).joined(separator: "-"))|\(appKey)"
    }

    /// One line for the settings screen, so "learning is on" is never an unverifiable claim.
    static func status() -> String {
        let policy = load()
        guard !policy.isEmpty else { return "no policy learned yet" }
        let exemplars = policy["exemplar_count"] as? Int ?? 0
        let signatures = policy["signature_count"] as? Int ?? 0
        let stamp: String
        if let when = policy["generated_at"] as? Double {
            let formatter = DateFormatter()
            formatter.dateFormat = "yyyy-MM-dd"
            stamp = formatter.string(from: Date(timeIntervalSince1970: when))
        } else {
            stamp = "unknown date"
        }
        return "\(exemplars) exemplar(s), \(signatures) allowance(s), learned \(stamp)"
    }
}
