"""Client side of the experimental false-alarm learner.

The learner itself lives at `learner/` in the repo root and is deliberately kept out of the app:
it is offline, stdlib-only, and reads the judgement log to produce one portable artefact,
`focus_policy.json`. This module is the *only* thing the running app knows about it — a small,
defensive reader that turns that artefact into three answers:

    prompt_suffix   extra lines appended to the classifier prompt ("the user has confirmed that
                    Khan Academy in Chrome IS part of maths revision")
    pre_allow       skip the check entirely for a signature the user has repeatedly excused
    threshold       don't block an off-task verdict below this confidence

Everything here fails soft. The learner is experimental and the policy file is generated by a
separate program; if it is missing, stale, from a future schema, or outright corrupt, the app
must behave exactly as it does with no learning at all. That is why every function has a plain
default and why the whole module is wrapped in try/except at the call site too.
"""

import json
import sys
import time
from pathlib import Path

from ..paths import data_dir

POLICY_FILE = data_dir() / "focus_policy.json"

# The schema this client understands. A policy file claiming a newer schema is ignored rather
# than half-read — a partially-understood policy is worse than none, because the parts we drop
# might be the safety limits.
SUPPORTED_SCHEMA = 1

# Hard client-side floor. Even if a policy file asks for a higher bar, we never require more than
# this much confidence to block: that is the ceiling on how far learning is allowed to erode the
# monitor, and it lives here — in the app — rather than in the learner, so that editing the
# generated file by hand cannot lift it.
MAX_THRESHOLD = 0.85
MAX_SUFFIX_CHARS = 1200
POLICY_MAX_AGE_DAYS = 60

_cache = {"mtime": None, "data": None}


def _repo_root() -> Path:
    """…/windows/guardian/focus/learned.py -> …/ (the repo root, where `learner/` sits)."""
    return Path(__file__).resolve().parents[3]


def _load() -> dict:
    """Read + cache the policy file, reloading only when it changes on disk."""
    try:
        mtime = POLICY_FILE.stat().st_mtime
    except OSError:
        _cache["mtime"], _cache["data"] = None, None
        return {}
    if _cache["mtime"] == mtime and _cache["data"] is not None:
        return _cache["data"]

    try:
        data = json.loads(POLICY_FILE.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError("not an object")
    except Exception:
        data = {}

    if data.get("schema") != SUPPORTED_SCHEMA:
        data = {}
    # A policy learned from a person's habits two months ago is describing a different person's
    # week. Expire it rather than trusting it indefinitely.
    generated = data.get("generated_at")
    if isinstance(generated, (int, float)):
        if time.time() - generated > POLICY_MAX_AGE_DAYS * 86400:
            data = {}

    _cache["mtime"], _cache["data"] = mtime, data
    return data


def _via_learner(task: str, app: str, title: str):
    """Prefer the learner's own `apply()` when the package is importable, so the matching logic
    lives in exactly one place and the app can't drift from it. Returns None when unavailable."""
    root = str(_repo_root())
    try:
        if root not in sys.path:
            sys.path.insert(0, root)
        from learner import policy as learner_policy       # noqa: PLC0415
    except Exception:
        return None
    try:
        return learner_policy.apply(_load(), task=task, app=app, title=title)
    except Exception:
        return None


def decide(task: str, app: str, title: str = "") -> dict:
    """The one call the monitor makes. Always returns a usable dict."""
    default = {"prompt_suffix": "", "pre_allow": False, "block_threshold": 0.0}
    data = _load()
    if not data:
        return default

    result = _via_learner(task, app, title)
    if not isinstance(result, dict):
        return default

    suffix = str(result.get("prompt_suffix") or "")[:MAX_SUFFIX_CHARS]
    threshold = result.get("block_threshold", 0.0)
    try:
        threshold = min(max(float(threshold), 0.0), MAX_THRESHOLD)
    except (TypeError, ValueError):
        threshold = 0.0
    return {
        "prompt_suffix": suffix,
        "pre_allow": bool(result.get("pre_allow")),
        "block_threshold": threshold,
    }


def prompt_suffix(task: str, app: str, title: str = "") -> str:
    return decide(task, app, title)["prompt_suffix"]


def status() -> str:
    """One line for the settings screen, so "learning is on" is never an unverifiable claim."""
    data = _load()
    if not data:
        return "no policy learned yet"
    n = data.get("exemplar_count", "?")
    sigs = data.get("signature_count", "?")
    when = data.get("generated_at")
    stamp = time.strftime("%Y-%m-%d", time.localtime(when)) if when else "unknown date"
    return f"{n} exemplar(s), {sigs} allowance(s), learned {stamp}"
