package com.lockoutprotocol.guardian.focus

import android.content.Context
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import org.json.JSONObject

/**
 * Client side of the experimental false-alarm learner.
 *
 * The learner itself lives at `learner/` in the repo root and is deliberately kept out of the app:
 * it is offline, stdlib-only Python, and reads the judgement log to produce one portable artefact,
 * `focus_policy.json`. This object is the only thing the running app knows about it — a small,
 * defensive reader that turns that artefact into three answers:
 *
 *  - [Decision.promptSuffix] — extra lines appended to the classifier prompt ("the user has
 *    confirmed that Khan Academy in Chrome IS part of maths revision")
 *  - [Decision.preAllow] — skip the check entirely for a signature the user has repeatedly excused
 *  - [Decision.blockThreshold] — don't block an off-task verdict below this confidence
 *
 * Everything here fails soft. The policy file is generated by a separate program and is copied
 * onto the device by hand (see `learner/README.md`); if it is missing, stale, from a future schema,
 * or corrupt, the app must behave exactly as it does with no learning at all.
 */
object LearnedPolicy {

    /**
     * The schema this client understands. A policy claiming a newer schema is ignored rather than
     * half-read — a partially-understood policy is worse than none, because the parts we drop
     * might be the safety limits.
     */
    private const val SUPPORTED_SCHEMA = 1

    /**
     * Hard client-side floor. Even if a policy file asks for a higher bar, we never require more
     * than this much confidence to block. This is the ceiling on how far learning may erode the
     * monitor, and it lives here — in the app — so editing the generated file by hand cannot
     * lift it.
     */
    const val MAX_THRESHOLD = 0.85
    const val MAX_SUFFIX_CHARS = 1200
    private const val MAX_AGE_DAYS = 60L

    private const val FILE_NAME = "focus_policy.json"

    data class Decision(
        val promptSuffix: String = "",
        val preAllow: Boolean = false,
        val blockThreshold: Double = 0.0,
    )

    private var cachedModified: Long = -1
    private var cached: JSONObject? = null

    private fun file(ctx: Context) = File(ctx.filesDir, FILE_NAME)

    /** Read + cache the policy file, reloading only when it changes on disk. */
    @Synchronized
    fun load(ctx: Context): JSONObject? {
        val f = file(ctx)
        if (!f.exists()) {
            cachedModified = -1
            cached = null
            return null
        }
        val modified = f.lastModified()
        if (modified == cachedModified) return cached

        var data = runCatching { JSONObject(f.readText()) }.getOrNull()

        if (data != null && data.optInt("schema", -1) != SUPPORTED_SCHEMA) data = null
        // A policy learned from a person's habits two months ago is describing a different person's
        // week. Expire it rather than trusting it indefinitely.
        if (data != null) {
            val generated = data.optDouble("generated_at", 0.0)
            val ageSeconds = System.currentTimeMillis() / 1000.0 - generated
            if (generated > 0 && ageSeconds > MAX_AGE_DAYS * 86_400) data = null
        }

        cachedModified = modified
        cached = data
        return data
    }

    /**
     * The one call the monitor makes. Always returns a usable value.
     *
     * The matching is done offline: the compiled artefact carries a pre-expanded `decisions` map
     * keyed by `"<task-phrasing>|<app>"`, so every client is a string lookup rather than a
     * reimplementation of the learner's clustering — which would inevitably drift.
     */
    fun decide(ctx: Context, task: String, app: String, title: String = ""): Decision {
        val policy = load(ctx) ?: return Decision()
        val decisions = policy.optJSONObject("decisions") ?: return Decision()
        val entry = decisions.optJSONObject(lookupKey(task, app)) ?: return Decision()

        val suffix = entry.optString("prompt_suffix", "").take(MAX_SUFFIX_CHARS)
        val threshold = entry.optDouble("block_threshold", 0.0).coerceIn(0.0, MAX_THRESHOLD)
        var preAllow = entry.optBoolean("pre_allow", false)

        // A pre-allow keyed only on the app, with no title evidence behind it, is too blunt to
        // honour — it would silently un-watch a whole app. Require the learner to have said which
        // titles it meant.
        if (preAllow) {
            val patterns = entry.optJSONArray("title_patterns")
            val count = patterns?.length() ?: 0
            preAllow = if (count == 0) {
                false
            } else {
                val lowered = title.lowercase()
                (0 until count).any { lowered.contains(patterns!!.optString(it).lowercase()) }
            }
        }

        return Decision(promptSuffix = suffix, preAllow = preAllow, blockThreshold = threshold)
    }

    fun promptSuffix(ctx: Context, task: String, app: String, title: String = ""): String =
        decide(ctx, task, app, title).promptSuffix

    /**
     * Normalise a task the same way the learner does when it builds the keys: lowercase, letters
     * and digits only, drop stopwords and words of two characters or fewer, keep the first four,
     * join with "-". Both sides must agree character for character, so it is small on purpose and
     * mirrored in `learner/policy.py:lookup_key` and `macos/.../LearnedPolicy.swift`.
     *
     * The app id is lower-cased too. On Android a package name is conventionally lower-case, but
     * not required to be, and the learner lower-cases before writing the key — so skipping it here
     * would make a lookup miss silently for anyone with a mixed-case package.
     */
    fun lookupKey(task: String, app: String): String {
        val stop = setOf("the", "a", "an", "my", "for", "on", "to", "of", "and", "in",
            "working", "work", "doing", "do", "some", "this", "that")
        val words = task.lowercase()
            .map { if (it.isLetterOrDigit()) it else ' ' }
            .joinToString("")
            .split(' ')
            .filter { it.isNotEmpty() && it !in stop && it.length > 2 }
            .take(4)
        return "${words.joinToString("-")}|${app.trim().lowercase()}"
    }

    /** One line for the settings screen, so "learning is on" is never an unverifiable claim. */
    fun status(ctx: Context): String {
        val policy = load(ctx) ?: return "no policy learned yet"
        val exemplars = policy.optInt("exemplar_count", 0)
        val signatures = policy.optInt("signature_count", 0)
        val generated = policy.optDouble("generated_at", 0.0)
        val stamp = if (generated > 0) {
            SimpleDateFormat("yyyy-MM-dd", Locale.US).format(Date((generated * 1000).toLong()))
        } else {
            "unknown date"
        }
        return "$exemplars exemplar(s), $signatures allowance(s), learned $stamp"
    }
}
